### PR TITLE
[HPARK-295] - Add a callback to perform business logic before redirection

### PR DESCRIPTION
**Pull request by evaldez-gs**
**Changes:**

- Add option to include a callback to perform business logic and also change final url (e.g. add query parameters)
- Remove wrong description for additional columns

### CODE REVIEW

**Review by mchaisse — CHANGES_REQUESTED** [review]
@evaldez-gs can you add a test and specify in the `README.rdoc` the parameter given to the proc?

**Comment by evaldez-gs** [comment]
@mchaisse Sure, I'm going to include the spec. The README is already included over configuration section.

**Comment by mchaisse** [comment]
@evaldez-gs my bad, sorry, `README` looks good 👍

**Comment by evaldez-gs** [comment]
@mchaisse Specs added for new configuration param, thanks!

**Review by mchaisse — APPROVED** [review]

**Pull request merged**
